apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: piconn/backend
          ports:
            - containerPort: 3000
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: piconn-database-keys
                  key: USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: piconn-database-keys
                  key: PASSWORD
            - name: MONGO_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: piconn-database-keys
                  key: MONGO_ADDRESS
            - name: MONGO_SHARD
              valueFrom:
                secretKeyRef:
                  name: piconn-database-keys
                  key: MONGO_SHARD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: piconn-JWT
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 3000
